# define STD_RATIO_SCREEN		1.765625
# define STD_WIDTH				640
# define STD_HEIGHT				360
# define CNT_BASE_COLOR			18
# define CNT_SETTED_COLOR		2
# define CNT_TEXTURE			4
# define CNT_RULE				CNT_BASE_COLOR + CNT_SETTED_COLOR + CNT_TEXTURE
# define CNT_TYPE_RULE			3